{
    'name':'school',
    'data':[
        'data/student_data.xml',
        'views/school_student_view.xml',
        'reports/report.xml',
        'reports/student_info.xml',
        'reports/student_report_template.xml',
    ]
}